---
info:
  application: RentMe connected trucks Demo
  show: Spring One 2GX 2015

endpoints:
  restart: enabled

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    region: default
    registryFetchIntervalSeconds: 5

